sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product tstn-003
env:
  global:
    -
      # LTD_AWS_ID
      secure: Y3tx3k652V9GZfrZAuXwwFry8j5vlLp6cNHfim5E+6V9MYMBldhxTKT+fzUhZ3U4lbpCGSjlhPdPDX0JVVIF1DslJlFXSanOyiQD/0y0J0pRgHjwJObNWLSXYme8n375/YoGoqPAMvnDl0JrLyPeYDTB78l8u2QFVdjTAnG47gu+ZaAPq+aEIXncD+zvt8Pinyw2JzVtFS1u7UGuKFUGasIF3cg5XOcFuNiWYMEljuD7LmrIx7QWvVi4EUY4EmsHYU7jVQOd34BUzNWB3Y5mQ0NNoGdGhIoV9cNlmE5YOKfzhbuKO/0SdwrEGzeS5MFv7DA5IdpM5CNCR9f3B9UpkpHu5MWC7yjwFByTLNw/YRFO8bzo7E49uu5f53R96YrailpKkxsf8amVWX4H0RLaxM5Gtm9pUJeLOox/FYksC7kS+g26Z+M7J3ij3Mz/IlsI8K3C5n+PYe3I4fE6kBq7f04kSeORQRlQbMw5TW5jngcCQxZ3QhXIc08deqIKV+FGOdcKGWPUctogUa6cSI2DxF7WaCJH6moECCsBiJNmpaB2uP8pA4Y8xFcBdCInAD7fIh56wrrUXKb3fSifH/X3uKMPbH5WfXZouv4jSgAGnOcpRhpz0+fz7YMJBqlcwSZjPZopJ9ID25Wvb4k24nLPLJqJBRmXHZYKd5Xdi3QhuRU=
    -
      # LTD_AWS_SECRET
      secure: JXNbmzYcP638NIdrzMJ8ke3263nCYwMFf04llZIBNYkNL5vYcwkIGXyJFXkcmEy7WpKEUB8ySTr43/FklyHRR2qzt49SndnaRcrmTlJv8+rEhjKhGdB3mF2rdML9AoO7N6MstTYZg+Mj9AiX6+gnxENaN22NfyRMa5BBWfEM93O8Ct7dyJSLHA2OdgmbFpwwGrX8OliSMwlfSofiaGqzsVJaTcIqX86Szx92oq+HJ3DYs3QJkzeurF+HGZze3mHBF4elT7gDRRDxeHODS7DJ5tH+Oi3Za75crUevQTXZqh8n0tRkkPSaqvLniyJdPvB7a8AWbtKKz82T0h/NvdwLMxYjnz7SpV6FAuiUlgI+6kzCMI0YGNbjCY1Mm/QhZZP/eq4sqiSD5MkwD670G6IHni5eUMhAA4zY4dUMHbfT2WFspEO3CvTBlDblJSUIqNgWpqWnC+vRmdh9yUXBbLyYVJS42Ne7n4e83TO9ncv0RODmoIcTmxv0SiDsqaQiU+dDC+WJFVKpqyvSC1gpgQMu9bVdp0xdckSOCWfX9aQ4fOpMlvTc5HAm1xX/x2UdX/aQ+7fH4r4Pj5zkikV9JcF93OBg72Kix+BZCOzGIZIdOREAXvICM5zXp+bLD/gTyYDX3MkML7c90xcxyh7fGU2oXsBWuMnPmIK1q0nMVV6/ScY=
    -
      # LTD_USERNAME
      secure: HyBP8sOSA7lZzu39ZXZEuxV61OFG6wxEkYNziZDgx5gQw+h7FGX1ER+Qz07pUBjUCDCRlNb48R1dQ3bC9KS/UQGetJghsXbQKoIsfmZhw6pRMoDWM2vO8lKr09hcrBkOHYqotzuMbAD4ra7M/CW/GCvHvlKVTJzchjyKKQmTdaPy6Dg61wjf7J70dR/ewMmBIse0rHDRZjdUG70j1naTeV+B4fEwiIDsmOxvcmQKWSwpWij8LPhxpff4ENQ75tn7vetaBWYEDE4YEVZCixwYin64TmDsXxPRBdg/U7cUr5qHT7YMdVMJFi0yg1ybmZBzc386HX8Pt0zsYkFOMRo4aePZHfjhQssBFvbwQpq2E87fez8hmEC0Z0kQWjeHEts0HrvWv49cb53Wx2r132edh0PB3hvVOA9ZSoUjZWGhsiOrzdjOBjFwPvhsaxnRoXNT7UgyRT8iwHoCZBglLxNe5ImmBx4pB5dBHW+fhejHgXx0KuAV7P2lIL+nXJwWBw+TCu8Ys/4tr/A2njBz0uxoLrnLOmA+mqTnCEHwj3DfAIua9Bxz+MIbDkD+ItpZRyhPlLVQ7JexgKH2UaoPsqYh8Y+cCbMKwkG4DziDYKPT6DvsjtgS0E1vwpwnGfVCtfatTP6LMBsaBKgf9P4+p1mfmDRag4a27qKeeG4YqFwFVQI=
    -
      # LTD_PASSWORD
      secure: duL56QPLGknEgNCVr8QlYTnnZYMhabMooU52gH8TrxWY7dZwyWAXaaXOb7hEPY/nXIt0+GSkL5obPfjbn0LndBbtNE0+KLKULmGVkBGl3Z1Kdx/FPDiSTO61izQ3nsuz4dQeARxOIZml355XaiIpTdowYRj8ILe3mV+xZ3vI9dZnUjddVLy65gu+GayeQ8UxYeX8BsHQFaLHNJSu56uel1w1aXnGIb9wxaPgzCxgIZh0JhubRSwtnDwCoWxDcydx/k9jf7MUUPKJ2/1fKqKkuj4AOE+jIr1ry8fERMnYBMMtjZ4/KnG1GAnyCJNGaOlupFzJJoTGNvLXhYdDMB8PkyDUnlKRC9HtAm99yh7N1MIsrJqNMqmhJW+X9I9HLUXIGvy26ojDkrsVlPl8O79ehRCvbcjelsFTyhM9akGwOcAFR4lveZIsaGObd3OrWT1PfVm1/3sdfuCD5WCaJWGknU+XKNshCWkCTKink8Muczz1J7rPBT5Pn0FzJov/am6cj3EtYJ4gr8MWIxKVumH2eQ2oD1ZDEV5ffj0KD7CkR0bCKp1n2CDSQ74LiSX5X7WzCGOeDov7YQUDlrQ1YbsDoDQRMJdlw5c8NLdCDIbPvDqtYh83Lg9zd6vXCC+K2R+5YmBXf1pF3o3/NVbrCjwXWU3KZKHupA7nl5FWthMFILE=
